### PR TITLE
[ready to merge] photon sharing implementation

### PR DESCRIPTION
**Pull request by yaoruoyang**

### CODE REVIEW

**Comment by fangq** [comment]
also, would be great to think of a way to include new input but keep the input file backward compatible. the change you made seems make the new binary can not read older input files. if this is a problem, we can only allow users to specify srcnum in json input, not the inp input.

**Comment by yaoruoyang** [comment]
Sure, I will work out a solution.

**Comment by yaoruoyang** [comment]
Have reverted the white-space changes. Will address the back-compatibility issue tomorrow.

**Comment by yaoruoyang** [comment]
Hi Dr. Fang. I've modified the codes as you suggested to ensure backward compatibility. Can you review the codes again and maybe give some feedback?

**Pull request merged**
